name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install rust/cargo
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
<<<<<<< HEAD
        
      - name: install I2Pd
        run: sudo add-apt-repository ppa:purplei2p/i2pd -y && sudo apt-get update -y && sudo apt-get install i2pd -y
      
      - name: test
        run: |
          i2pd --daemon
          RUST_LOG=trace $HOME/.cargo/bin/cargo test -- --test-threads 1
=======

      - name: install NANO
        run: |
          sudo apt install unzip
          wget "https://github.com/syvita/nano/releases/download/v0.0.2/NANO-linux.v0.0.2.zip"
          unzip NANO-linux.v0.0.2.zip -d .
          chmod 777 ./NANO-linux.v0.0.2/router/bin/i2p-zero

      - name: test
        run: |
          ./NANO-linux.v0.0.2/router/bin/i2p-zero > log &
          (tail -f -n0 log &) | grep -q "NANO is running, you can make SAM requests now"
          sleep 25
          RUST_LOG=trace $HOME/.cargo/bin/cargo test -- --test-threads 1 --nocapture
>>>>>>> ad84b8ba13df8bc7f478157e9105659dca2812df
