name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-cargo
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: cargo test
        run: cargo build --all && cargo test --all --no-run
      # - name: install NANO
      #   run: |
      #     sudo apt install unzip
      #     wget "https://github.com/syvita/nano/releases/download/v0.0.2/NANO-linux.v0.0.2.zip"
      #     unzip NANO-linux.v0.0.2.zip -d .
      #     chmod 777 ./NANO-linux.v0.0.2/router/bin/i2p-zero
      #
      # - name: test
      #   run: |
      #     ./NANO-linux.v0.0.2/router/bin/i2p-zero > log &
      #     (tail -f -n0 log &) | grep -q "NANO is running, you can make SAM requests now"
      #     sleep 25
      #     RUST_LOG=trace $HOME/.cargo/bin/cargo test -- --test-threads 1 --nocapture